### ISSUE TITLE
Remove redundant logic for `type_auth == "ActiveDirectoryIntegrated"`

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-msft/dbt-sqlserver#101]
This piece of code does not do anything. It tries to remove the element in the list with value `"UID={None}"`, however that element is never created, therefore it can also not be removed

https://github.com/dbt-msft/dbt-sqlserver/blob/0d529de2641cc7e3f84bab47e22a9f4c80629bbd/dbt/adapters/sqlserver/connections.py#L238-L240

**Comment by swanderz** [comment]
yeah 100%. I actually want to remove all reference to `ActiveDirectoryIntegrated` as it has nothing to do with Azure. Instead, it pertains to on-prem Active Directory which is rather old-school and unsupported at this point.

**Comment by JCZuurmond** [comment]
Ok, so we are quite sure nobody is using that? It would clean up the code

**Comment by swanderz** [comment]
Yep! We couldn't even get it working on our end

**Comment by swanderz** [comment]
resolved a few months ago
