### ISSUE TITLE
Save dbt-tags to Extended Properties for tables/views

### ISSUE THREAD

**Issue by larsjohanssonblank** [dbt-msft/dbt-sqlserver#109]
Would it be possible to add tags defined in the dbt model to Extended Properties for a table/view?

Would be useful to be able to have the documentation/tags embedded in the table/views, so that tou could generate reports on extended prop (the use case is to tag/mark tables/views if they contains sensitive personal data (GDPR etc)

https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-addextendedproperty-transact-sql?view=sql-server-ver15

**Comment by swanderz** [comment]
I think this is a really cool idea! Especially if it could easily surfaced inside of Purview for example. I know that Big Query let's you do this, but have you seen any cool examples of people using the extended prop feature w/ TSQL?

**Comment by larsjohanssonblank** [comment]
i don't know if the usage is cool like Jägermeister cool ;-), but it goes well with the principle of keeping documentation as near as the code as possible, and being able to tag tables/views and even columns if one would like, is a good example of a self documenting database.

**Comment by swanderz** [comment]
closing in favor of #134
