### ISSUE TITLE
Changing the database via {{ config(database='OTHER_DB') }} doesn't work

### ISSUE THREAD

**Issue by panasenco** [dbt-msft/dbt-sqlserver#110]
My default database name is `EDW_BDM` but I'm trying to create this one view in a different database `FI_DM_EBI`.

sqlserver.sql:
```
{{ config(database='FI_DM_EBI') }}
SELECT
  'a' AS col1,
  'b' AS col2
```

`dbt run` prints `START view model FI_DM_EBI.dbo.sqlserver` and dbt docs show below database structure:

![image](https://user-images.githubusercontent.com/5506411/108249421-e83eb480-7109-11eb-9b14-23261fca3b00.png)

However, the view still gets created in `EDW_BDM`. Looking at debug output, the connection string used is the default one that has the database `EDW_BDM`.

The same thing happens when changing the database name in `dbt_project.yml`:
```
models:
  hopedw:
    example:
      database: FI_DM_EBI
```

Please add support for changing the database.

**Comment by dubravcik** [comment]
same here.
Moreover, my model was incremental and `dbt run` dropped it (even though it has ` full_refresh = false`)  due to the bug :D
