### ISSUE TITLE
add integration testing for SQL Server pre-2016

### ISSUE THREAD

**Issue by dataders** [dbt-msft/dbt-sqlserver#112]
one challenge is that it looks like SQL Server 2017 (`14.0.1000.169-2`) is the oldest version of SQL Server to run on Linux. So the challenge would be to build a Windows-based Docker image that installs an older version?

Alternatively we could host an older version somewhere instead of Dockerizing it?

**Comment by mikaelene** [comment]
I think we have to run a vm with windows on it.

**Comment by sdebruyn** [comment]
@dataders @mikaelene Do you think this is still relevant? Microsoft mainstream support has ended for these versions. I don't think we should be offering more support than Microsoft here.
