### ISSUE TITLE
Use `tox` for all integration tests

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-msft/dbt-sqlserver#131]
# Background
We currently run some integration test outside of `tox`. See [circle CI config](https://github.com/dbt-msft/dbt-sqlserver/blob/master/.circleci/config.yml), for example [this line](https://github.com/dbt-msft/dbt-sqlserver/blob/5fb850e26d7131628859dea51710e53ddb6181b3/.circleci/config.yml#L53).

# Summary
Let's move these integration test to `tox` so that we have a uniform way of testing. 

# Approach
The tests in dbt calls the [`handle_and_check`](https://github.com/fishtown-analytics/dbt/blob/2b48152da66dbd7f07272983bbc261f1b6924f20/core/dbt/main.py#L181) method. Apparently it [returns if it ran successfully](https://github.com/fishtown-analytics/dbt/blob/2b48152da66dbd7f07272983bbc261f1b6924f20/core/dbt/main.py#L206), see [here](https://github.com/fishtown-analytics/dbt/blob/7ec5c122e17ab7e1a5dd1e1cab36527159564a0f/test/integration/base.py#L571) for how they us it. 

We can do the same:
1. Pass in the CLI arguments to `handle_and_check` from test in python.
2. Check if successful.

**Comment by JCZuurmond** [comment]
For context, [this dbt PR](https://github.com/fishtown-analytics/dbt/pull/3204). Makes the tox setup more similar to what we have.

**Comment by sdebruyn** [comment]
Looks like a good time to implement this together with #216

**Comment by sdebruyn** [comment]
The integration tests have been refactored to the new dbt adapter test package and are all triggered with tox now
