### ISSUE TITLE
Incremental Model Fails When Column Varchar Size Increases (Edge Case)

### ISSUE THREAD

**Issue by alittlesliceoftom** [dbt-msft/dbt-sqlserver#133]
When an incremental model's varchar size increases beyond the current default e.g. from VARCHAR(50) - (150) , dbt attempts to replace the column, however it makes syntax errors in SQL server: 

**Actual**
```
ALTER TABLE database.schema.model
ADD COLUMN "Column__dbt_alter" CHARACTER VARYING(200);
```

**Desired**
```
ALTER TABLE database.schema.model
ADD "Column__dbt_alter" VARCHAR(200);
```

I may be able to add a MRE later. 

Dbt 0.19.1

**Comment by sdebruyn** [comment]
fixed in #376
