### ISSUE TITLE
dbt jaffle shop demo doesn't work on adapter

### ISSUE THREAD

**Issue by owlas** [dbt-msft/dbt-sqlserver#136]
**Minimum working example**

Here's my directory
```
.
├── docker-compose.yml
├── dockerfile
├── jaffle_shop  # is this repo https://github.com/fishtown-analytics/jaffle_shop
└── profiles.yml
```

```dockerfile
# dockerfile
FROM python:3.8

RUN \
  export ACCEPT_EULA=Y && \
  apt-get update && \
  apt-get install -y --no-install-recommends curl g++ unixodbc-dev && \
  curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
  curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
  apt-get update && \
  apt-get install -y --no-install-recommends msodbcsql17 && \
  pip install dbt dbt-sqlserver

COPY ./jaffle_shop/ /usr/src/app
COPY profiles.yml /root/.dbt/profiles.yml

WORKDIR /usr/src/app

CMD ["dbt", "debug"]
```

```yaml
# profiles.yml
config:
  partial_parse: false
  send_anonymous_usage_stats: false

jaffle_shop:
  target: jaffle
  outputs:
    jaffle:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | as_number }}"
      database: tempdb
      schema: jaffle
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASS') }}"
```

```yaml
# docker-compose.yml
version: "3.1"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!
  dbt:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASS=Password!
```

**Steps to reproduce**

In one terminal run the following commands in the dbt container. This shows that the profile is setup correctly, it creates the seed tables, and then successfully creates 3 views `stg_orders,stg_customers,stg_payments` and 2 tables `customers, orders`

```shell
docker compose run dbt /bin/bash
dbt debug # works
dbt seed # works
dbt run # works
```

So by the end you should see:
```text
# dbt run 
Running with dbt=0.19.1
Found 5 models, 20 tests, 0 snapshots, 0 analyses, 153 macros, 0 operations, 3 seed files, 0 sources, 0 exposures

18:21:54 | Concurrency: 1 threads (target='jaffle')
18:21:54 | 
18:21:54 | 1 of 5 START view model jaffle.stg_orders............................ [RUN]
18:21:54 | 1 of 5 OK created view model jaffle.stg_orders....................... [OK in 0.09s]
18:21:54 | 2 of 5 START view model jaffle.stg_payments.......................... [RUN]
18:21:54 | 2 of 5 OK created view model jaffle.stg_payments..................... [OK in 0.04s]
18:21:54 | 3 of 5 START view model jaffle.stg_customers......................... [RUN]
18:21:54 | 3 of 5 OK created view model jaffle.stg_customers.................... [OK in 0.05s]
18:21:54 | 4 of 5 START table model jaffle.orders............................... [RUN]
18:21:54 | 4 of 5 OK created table model jaffle.orders.......................... [OK in 0.07s]
18:21:54 | 5 of 5 START table model jaffle.customers............................ [RUN]
18:21:54 | 5 of 5 OK created table model jaffle.customers....................... [OK in 0.04s]
18:21:54 | 
18:21:54 | Finished running 3 view models, 2 table models in 0.36s.

Completed successfully
```

While that is still running, in another terminal run:
```sql
docker compose exec db /opt/mssql-tools/bin/sqlcmd -S db -U sa -P Password!
1> select * from jaffle.stg_customers
2> go
# ok
1> select * from jaffle.customers
2> go
# Invalid object name 'jaffle.customers'.
```

**Expected**

I was expecting the `jaffle.customers` table to exist since dbt was successful

---
I hope the example helps. Have I missed anything?

**Comment by swanderz** [comment]
@owlas sorry for your trouble here -- I think the problem is two-fold:
1. there is something about the repo that isn't SQL Server compatible out of the box. there have been various versions of the jaffle_shop projects and various forks that are SQL Server compatible:
    1. https://github.com/jacobm001/jaffle_shop_mssql
    2. https://github.com/dbt-msft/jaffle_shop_mssql
2. there is a bug introduced in dbt-sqlserver version `v0.19.1` that doesn't surface errors happening on the server like it used to.

If you don't mind could you:
1. install dbt-sqlserver from github (`pip install git+https://github.com/dbt-msft/dbt-sqlserver.git`),
2. try running the jaffle_shop again to see the errors you couldn't see before
3. use the other jaffle_shop projects listen above for ideas on how to fix errors

**Comment by owlas** [comment]
Hey @swanderz sorry for the delay, will try this out today. Thanks for looking into it!

**Comment by swanderz** [comment]
> Not sure if I've done something wrong but installing from the repo is taking a very long time. Currently sitting at 110 minutes trying to install pip dependencies

ouch -- definitely not normal! the bugfix version has been published to PyPI, so `pip install dbt-sqlserver==0.19.2` should suffice now.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/8158673/124830767-39233e00-df2f-11eb-9706-8fc8e4e7eb0c.png">

**Comment by owlas** [comment]
Nice! I'll try the new pip package

**Comment by swanderz** [comment]
@owlas lmk if you're still experiencing this issue
