### ISSUE TITLE
Seed file without data rows causes "max() arg is an empty sequence" error

### ISSUE THREAD

**Issue by DVTimWilson** [dbt-msft/dbt-sqlserver#146]
Using a seed file containing only column headers and the dbt-snowflake adapter, the command "dbt seed --select seedfilename --full-refresh" creates an empty seedfilename table in Snowflake. With the dbt-sqlserver adapter v0.19.1, however, I get a "max() arg is an empty sequence" error and no table is created in MSSQL.

The error occurs in dbt/adapters/sqlserver/impl,py line 22. I am working around the error by replacing this line with
`max_len = max(lens) if len(list(column.values_without_nulls())) else 64`

**Comment by swanderz** [comment]
quick question -- can you do this in other adapters? I'm scouring [dbt's default seed materialization](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/include/global_project/macros/materializations/seed/seed.sql) and I can't see anything just yet that would allow for this behavior...

this line?
https://github.com/dbt-msft/dbt-sqlserver/blob/ab9b6fdd144d835430b4ea24d49c5c96e8983a48/dbt/adapters/sqlserver/impl.py#L22

TBH, I've never looked at that before... but if it works by all means open a pull request!

Another way of approaching this would be in the macro that loads rows to a seed table (see below). Here we might have a conditional that says something along the lines of
```sql
{% if agate_table.rows | length == 0 %}
    {# do nothing #}
{% else %}
    {# run the "insert into" statement #}
{% endif %}
```

https://github.com/dbt-msft/dbt-sqlserver/blob/ab9b6fdd144d835430b4ea24d49c5c96e8983a48/dbt/include/sqlserver/macros/materializations/seed/seed.sql#L1-L23

**Comment by swanderz** [comment]
did some more digging and looks like this issue also happened with the Redshift adapter and was fixed in https://github.com/fishtown-analytics/dbt/pull/2255

I'll make a quick PR that copies this fix and maybe you can try it out and see how it works?

**Comment by swanderz** [comment]
@DVTimWilson I just made a patch PR with #147, do you want to try and see if it fits your use case?
