### ISSUE TITLE
"Runtime Error list.remove(x): x not in list" when trying to connect to Azure SQL

### ISSUE THREAD

**Issue by jhoolachan** [dbt-msft/dbt-sqlserver#148]
Hello,

I am trying to connect to an Azure SQL DB using ActiveDirectoryIntegrated authentication and am receiving the following error:

"Runtime Error list.remove(x): x not in list"

I see from the documentation that there are some stipulations to using ActiveDirectoryIntegrated (i.e. machine's credentials are enabled, ADFS is installed and running) and while I can't 100% confirm those stipulations are true, I am able to log into the DB using ActiveDirectoryIntegrated in SQL Server Management Studio so I'm thinking those stipulations have all been met.

Do you have any suggestions for troubleshooting? The error itself doesn't provide much info.

Thank you!
Jordan

--
  Running with dbt=0.19.1
  dbt version: 0.19.1
  python version: 3.7.9
  python path: 
  os info: Windows-10-10.0.18362-SP0
  Using profiles.yml file at mypath\profiles.yml
  Using dbt_project.yml file at mypath\dbt_project.yml
  
  Configuration:
    profiles.yml file [OK found and valid]
    dbt_project.yml file [OK found and valid]
  
  Required dependencies:
   - git [OK found]
  
  Connection:
    server: myserver.database.windows.net
    database: mydb
    schema: prod
    port: 1433
    UID: None
    client_id: None
    authentication: ActiveDirectoryIntegrated
    encrypt: True
    trust_cert: False
    Connection test: ERROR
  
  dbt was unable to connect to the specified database.
  The database returned the following error:
  
    >Runtime Error
    list.remove(x): x not in list

**Comment by swanderz** [comment]
I've personally never gotten ActiveDirectoryIntegrated to work before... however, there's obvious fix to the error message we're currently seeing... remove these lines.

https://github.com/dbt-msft/dbt-sqlserver/blob/39d468ddfefb3829c553fe121fe51f4735f4c769/dbt/adapters/sqlserver/connections.py#L273-L275


Want to try and install the branch in #149 and let me know if it works (or the new error message)?
`pip install git+https://github.com/dbt-msft/dbt-sqlserver.git@swanderz-patch-2`

**Comment by jhoolachan** [comment]
Thank you for the speedy response! The fix solved the issue and I've confirmed that "dbt run" generates the expected output in the SQL DB.
