### ISSUE TITLE
Add adapter unique_field property

### ISSUE THREAD

**Issue by jtcohen6** [dbt-msft/dbt-sqlserver#157]
Hey dbt-msft team!

To make a long story short: As dbt adoption grows, our current way of answering the question, "How many companies/orgs/teams are using dbt?" has not scaled well. Historically, we've just used an MD5 hash of the user-defined project name (`name` field in `dbt_project.yml`). We've found that there are hundreds (potentially thousands) of distinct dbt projects all named things like `jaffle_shop` or `analytics`. So we'd like to start tracking another identifier, to help disambiguate projects and better understand adoption.

There's a fuller explanation over in https://github.com/dbt-labs/dbt/issues/3713, and the change in `dbt-core` in https://github.com/dbt-labs/dbt/pull/3796.

The desired change really just looks like adding a method [here](https://github.com/dbt-msft/dbt-sqlserver/blob/f2a480689825ac1194e26e6dc6427c4b6308ca02/dbt/adapters/sqlserver/connections.py#L63):
```python
    @property
    def unique_field(self):
        return self.host
```

dbt-core will take the MD5 hash and supply the result to its anonymous tracking context. The change is only needed in `dbt-sqlserver`, since the method will be inherited by `dbt-synapse` as part of `SQLServerCredentials`.

Of course, I'd be thrilled to share the improved data with adapter plugin maintainers. I'm looking into ways to share aggregated dbt adoption metrics with the community more broadly.

If you're up for it, I can open a PR. Would `host` be the best field to uniquely identify a team/organization building with `dbt-sqlserver`/`dbt-synapse` together?

**Comment by swanderz** [comment]
@jtcohen6 totally understand the rationale.

> Would `host` be the best field to uniquely identify a team/organization building with `dbt-sqlserver`/`dbt-synapse` together?

### thoughts
maybe I'm nitpicking, but `account` for Snowflake seems to make more sense for identifying teams/orgs than `host` for dbt-sqlserver.

1. we often have dev stg prod servers for a single dbt project. Hashing the host for this scenario would result in 3 teams/orgs. Is that the granularity you're trying to collect?
2. We're also planning to have a 1-1 mapping of dbt projects to databases, all hosted on the same host/server. Is this one team/org?

I don't have a good alternative beyond concatenating `host` with `database` and hashing that. perhaps that's too invasive?

@mikaelene @alieus what are y'all's initial impressions?

**Comment by alieus** [comment]
@swanderz  I'm definitely with you on that `host` is not the perfect identifier for us.  A single `org`  (or even a single team) can have multiple unique `hosts` . If each of these `hosts` is counted as a unique company/org/team, that would definitely be inaccurate. 

@swanderz  maybe I'm missing the point, but I don't see how concatenating `host` + `database` will solve this.

**Comment by swanderz** [comment]
close via #168
