### ISSUE TITLE
custom data tests with CTEs fail

### ISSUE THREAD

**Issue by swanderz** [dbt-msft/dbt-sqlserver#172]
## background
Per @alittlesliceoftom's [Slack thread](https://getdbt.slack.com/archives/C2JRRQDTL/p1604575110440800).
## Steps to reproduce:
1. write a data test that uses CTE clause,
2. dbt wraps the data test's query into another CTE.
3. Synapse returns an error because it does not allow for nested CTEs.

### `tests/example.sql`
```sql
WITH cte_test AS (
    SELECT * FROM {{ref('interesting_moments')}}
)
select TOP 0 * FROM cte_test
```
### `target/compiled/ava_its_data/tests/example.sql`
This doesn't work as Synapse does not allow a single `WITH` clause inside of 
```sql
with dbt__CTE__INTERNAL_test as (
WITH cte_test AS (
    SELECT * FROM "june_sql_pool"."ajs_mkt"."interesting_moments"
)
select TOP 0 * FROM cte_test
)select count(*) from dbt__CTE__INTERNAL_test
```

## potential workarounds
haven't thought much about the best solution yet...
### add the wrapped CTE to the end of the CTE chain?
Synapse doesn't support nested CTEs, but it does supported "chained referencing" of CTEs inside a single WITH clause. So the example below works, but I don't know how I would conditionally do this only when the data test has a CTE

```sql
WITH
cte_test AS (
    SELECT * FROM "june_sql_pool"."ajs_mkt"."interesting_moments"
),
dbt__CTE__INTERNAL_test AS (
    select TOP 0 * FROM cte_test
)
select count(*) from dbt__CTE__INTERNAL_test
```
### create and dispose of a view/ temp table instead of a CTE?
```sql
CREATE VIEW  dbt__CTE__INTERNAL_test as
WITH cte_test AS (
    SELECT * FROM "june_sql_pool"."ajs_mkt"."interesting_moments"
)
select TOP 0 * FROM cte_test;

select count(*) from dbt__CTE__INTERNAL_test

DROP VIEW dbt__CTE__INTERNAL_test
```

**Comment by swanderz** [comment]
close by #167

**Comment by alittlesliceoftom** [comment]
Hey @dataders, 

I'm not quite sure why #167  closes this issue? Could you clarify? 

I'm on 1.3.0 and ephemeral isn't currently working, and the docs https://dbt-msft.github.io/dbt-msft-docs/docs/dbt-synapse/overview/#table-materializations ref that ephemeral doesn't work rn (on synapse).
