### ISSUE TITLE
Release version mismatch

### ISSUE THREAD

**Issue by semcha** [dbt-msft/dbt-sqlserver#185]
@swanderz
pypi: https://pypi.org/project/dbt-sqlserver/#history - dbt-sqlserver==**0.21.0**
Release page: https://github.com/dbt-msft/dbt-sqlserver/releases/tag/v0.21.1 - **0.21.1**

**Comment by swanderz** [comment]
@semcha great catch -- thanks! I made a typo on the GitHub release and have since [corrected it](https://github.com/dbt-msft/dbt-sqlserver/releases/tag/v0.21.0). that'll teach me to publish releases while I'm in a meeting... 😵
