### ISSUE TITLE
fix CircleCI connection tests for Service Principals...

### ISSUE THREAD

**Issue by dataders** [dbt-msft/dbt-sqlserver#189]
@sdebruyn maybe you can help me with this? I may need to make new AAD apps and make the env vars available to circleci first?

two different failures happening:

## AZ SP auto
https://app.circleci.com/pipelines/github/dbt-msft/dbt-sqlserver/449/workflows/f83ea477-e779-45ac-befd-d1e0eecf1c78/jobs/1710

> Encountered an error:
> Runtime Error
>   secret should be an Azure Active Directory application's client secret

## AZ SP env
https://app.circleci.com/pipelines/github/dbt-msft/dbt-sqlserver/450/workflows/fedbabe9-9dc5-4224-92e9-99c705a6ac2f/jobs/1717

> Encountered an error:
> Runtime Error
>   EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
>   Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot.this issue.
> Exited with code exit status 2

**Comment by sdebruyn** [comment]
they are working now :)
