### ISSUE TITLE
unsupported lower case information_schema

### ISSUE THREAD

**Issue by TatianaLinnik** [dbt-msft/dbt-sqlserver#193]
I am trying to run dbt, but getting this error:
`Encountered an error: Database Error ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'WALRUS.information_schema.tables'`
Our SQLServer is case sensitive, so `information_schema.tables` doesn't exist (I double-checked by querying my database directly), but `INFORMATION_SCHEMA.TABLES` exists. Upper case information_schema is commonly used for SQLServer (https://docs.microsoft.com/en-us/sql/relational-databases/system-information-schema-vi[…]information-schema-views-transact-sql?view=sql-server-ver15).

**Comment by TatianaLinnik** [comment]
As I can see here https://github.com/dbt-msft/dbt-sqlserver/blob/aa0422f6467af6041562380efb7bdebbbc6bddd8/dbt/include/sqlserver/macros/adapters.sql you use everywhere Upper case `INFORMATION_SCHEMA.TABLES` except the macro `sqlserver__list_relations_without_caching(schema_relation)`. I can PR this little change.

**Comment by swanderz** [comment]
we'd love the PR, thanks @TatianaLinnik!

**Comment by TrololoLi** [comment]
I created PR, but one of the tests didn't pass due to the `('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')`. I also couldn't link the PR to this issue

**Comment by TrololoLi** [comment]
error is gone=)
