### ISSUE TITLE
 >Database Error   ('08001', '[08001] [Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:self signed certificate] (-1) (SQLDriverConnect)')

### ISSUE THREAD

**Issue by ogaly-absys** [dbt-msft/dbt-sqlserver#219]
Hi, I have an error with dbt debug and with the ODBC Driver 18 for SQL Server in my profiles file.
It'think the driver is configured by default with "TrustServerCertificate=Yes" 
it's resolved when i changed the driver to ODBC Driver 17.

**Comment by dataders** [comment]
great callout! I remember reading somewhere that there's a new option you must pass into the connection string for version 18 of the driver like `Something=True`, and now I can't find the doc anywhere! I'll update later when I find it

**Comment by dataders** [comment]
closing in favor of #269
