### ISSUE TITLE
character_maximum_length

### ISSUE THREAD

**Issue by nysthee** [dbt-msft/dbt-sqlserver#236]
Hi 

I am not able to ouput the `character_maximum_length` from columns coming from `get_columns_in_relation`. Does anyone know what could be the cause of this?

**Comment by sdebruyn** [comment]
Hi @nysthee 

Could you provide the output of `dbt --version`?

**Comment by nysthee** [comment]
dbt --version
08:01:07  Encountered an error:
Could not parse version "1.1.0.rc1"

**Comment by nysthee** [comment]
Same behaviour on 1.0.0 and 1.1.0.rc1.

**Comment by sdebruyn** [comment]
Alright, at least it does not impact the next release then. Could you share a little bit of code to reproduce this?
