### ISSUE TITLE
Incremental Strategy "Merge" is generating Delete, Insert into command

### ISSUE THREAD

**Issue by rezasoltanirezvandeh** [dbt-msft/dbt-sqlserver#246]
Merge strategy in incremental, generates delete and insert into command instead of the merge. 

`
{{
    config(
        as_columnstore= false, 
        materialized= 'incremental',
        incremental_strategy= 'Merge',
        unique_key='customer_code'
    )
}}
SELECT 
customer_code, customer_name
FROM {{ref('customer')}}
`

**The run script:**
`  
    delete from "......."."dim_customer"
    where (customer_code) in (
        select (customer_code)
        from "......."."#dim_customer__dbt_tmp"
    );
    insert into "......."."dim_customer" ("customer_code", "customer_name")
    (
        select "customer_code", "customer_name"
        from "......."."#dim_customer__dbt_tmp"
    );
`

**Comment by dataders** [comment]
thanks for the bug report @rezasoltanirezvandeh ! can you share what version of dbt-sqlserver you are using as well as what SQL Server product you are using? Cheers

**Comment by rezasoltanirezvandeh** [comment]
Hi @dataders,

here are the details:

_(base) reza@dbt:~/Desktop$ dbt --version
installed version: 1.0.7
   latest version: 1.1.0
Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation
Plugins:
  - sqlserver: 1.0.0 - Up to date!
(base) reza@dbt:~/Desktop$_ 

and I am using Azure SQL Database.
Cheers,
Reza

**Comment by hernanparra** [comment]
Same problem here on SQL Server 2017 with dbt 1.0.4 and sqlserver 1.0.0

**Comment by hernanparra** [comment]
The team of dbt-core did the refactoring in version 1.3. Is the incremental "merge" strategy working now?
