### ISSUE TITLE
support for offline install

### ISSUE THREAD

**Issue by vishalkhondre** [dbt-msft/dbt-sqlserver#259]
I'm trying to install package on machine where internet is restricted.

I'm following below link to install dbt-sqlserver however so far no luck!
https://stackoverflow.com/questions/36725843/installing-python-packages-without-internet-and-using-source-code-as-tar-gz-and

I performed below steps on machine where I've internet access
mkdir dbtsql
pip download dbt-sqlserver -d "/home/test/dbtsql"
tar cvfz dbtsql.tgz dbtsql

I performed below steps on machine where I don't have internet access 
tar xvfz dbtsql.tgz
cd dbtsql

I'm not sure on next steps. Any direction/ pointer on next steps will be great help!

**Comment by dataders** [comment]
@vishalkhondre you're almost there I think! Kudos to getting as far as you have, I've been using pip and python for 5 years and I think I'd struggle to make this happen without help.

I'm thinking the last thing that you need to do is call the below. At the risk of mansplaining, the command tells pip to install the package specified by `setup.py` in the directory given. So the `.` means the `dbtsql/` directory, in which there should be a `setup.py` which pip will use to install `dbt-sqlserver`. Let me know if that works!
```shell
pip install .
```

Also kind of guessing here, but I believe you don't have to unzip the `.tgz`, you can just call
```sh
pip install path/to/dbtsql.tgz
```

**Comment by vishalkhondre** [comment]
@dataders - Thank you so much for your response! I tried everything :-) no luck! 

- https://stackoverflow.com/questions/36725843/installing-python-packages-without-internet-and-using-source-code-as-tar-gz-and
- https://stackoverflow.com/questions/43314517/how-to-install-multiple-whl-files-in-cmd/43314623#43314623

I'm giving up with offline installation :-)

**Comment by dataders** [comment]
@vishalkhondre sorry to hear that! I appreciate your perseverance.
