### ISSUE TITLE
[BUG] Cannot recreate table with key constraint using post-hook because key in backup table is not renamed

### ISSUE THREAD

**Issue by rainermensing** [dbt-msft/dbt-sqlserver#281]
# Is this a new bug in dbt-core?
 * I believe this is a new bug in dbt-core or dbt-sqlserver
 * I have searched the existing issues, and I could not find an existing issue for this bug

# Current Behavior
I materialize as table and would like to add a primary key constraint uing a post-hook.

```
{{ config(
    post_hook=[
      "ALTER TABLE {{ this }} ADD CONSTRAINT PK_example PRIMARY KEY NONCLUSTERED (example_key)"
    ]
) }}
```

 This works fine on the first run. However, on the second run, I receive the following error:

```
('42S01', "[42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]There is already an object named 'PK_example' in the database. (2714) (SQLExecDirectW); [42S01] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Could not create constraint or index. See previous errors. (1750)")
```

I think I already found the reason: On a rerun, a backup table is created. The table gets a suffix '__dbt_backup'. However, the primary key in the table does not get a suffix.
![image](https://user-images.githubusercontent.com/31634583/187917602-300b8b62-aa80-4864-98c6-d89d389de116.png)

# Expected Behavior
The key in the backup table should be renamed, so that there are no name collisions with the post-hook query.

# Steps To Reproduce
Try to rerun the following model twice 
```
{{ config(
    materialized = 'table',
    post_hook=[
      "ALTER TABLE {{ this }} ADD CONSTRAINT PK_example PRIMARY KEY NONCLUSTERED (example_key)"
    ]
) }}

SELECT 1 as example_key
```

# Environment
```
dbt-core=1.1.1
dbt-sqlserver=1.1.0
ODBC Driver 18
Server: Azure SQLDatabse
```

# Additional Context
A couple things before anyone asks:
* yes, I know that you can enforce uniqueness and nullification using tests, 
* no, I also do not want to use incremental tables, i.e. just define the key once without a macro. I want to materialize as table.

**Comment by dataders** [comment]
@matsonj also, do you think constraints are something that should just be integrated into the materialization workflow? so then the renaming is taken care of automatically and isn't necessary to do as a post-hook?

**Comment by matsonj** [comment]
@dataders Good question. I am seeing a recurring theme of users wanting to use the config block to handle indexes ('the dbt way' of doing this) vs. using post-hooks w/sql statements (i.e. ALTER TABLE or DROP INDEX). There was a recent discussion in the dbt slack channel about this as well. It's further complicated because indexes are partially handled as part of this adapter, which defaults to columnstore indexes and can be modified in the config block. So of course it makes sense that you could also add clustered indexes using the config block. 

Long way of saying - if we are including index management in the scope of the adapter, we should probably handle all types of indexes.

**Comment by rainermensing** [comment]
> @matsonj also, do you think constraints are something that should just be integrated into the materialization workflow? so then the renaming is taken care of automatically and isn't necessary to do as a post-hook?

Hi @dataders, thanks a lot for your reply! Can you explain what you mean by materialization workflow?

**Comment by rainermensing** [comment]
> @rainermensing can you add `DROP INDEX [ IF EXISTS ]` to your post hook?

Hi @matsonj I think that is difficult. I have tried to do something like 

```
DROP INDEX IF EXISTS PK_example ON {{ this }}__dbt_backup 
```
but that throws an error...

```
('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Incorrect syntax near '__dbt_backup'. (102) (SQLExecDirectW)")
```

**Comment by matsonj** [comment]
Hi @rainermensing 

Here is a way to get this working for now:

```
{{ config(
    materialized = 'table',
    pre_hook=[
        "ALTER TABLE {{ this }} DROP CONSTRAINT PK_example;
        DROP INDEX IF EXISTS PK_example ON {{ this }}"
    ],
    post_hook=[
      "ALTER TABLE {{ this }} ADD CONSTRAINT PK_example PRIMARY KEY NONCLUSTERED (example_key)"
    ]
) }}

SELECT 1 as example_key
```

I just tested on SQL Server 2019 and it worked ok for me. 

> Can you explain what you mean by materialization workflow?

He is referring to how dbt 'builds' tables - i.e. how it interacts with the config block in this adapter. More or less suggesting that the pre/post hook as shown above is implemented in the adapter.

**Comment by matsonj** [comment]
hmm actually my code above doesn't work if the table doesn't already exist. Will have to noodle on how to solve this.
