### ISSUE TITLE
Integrate with dbt-elementary

### ISSUE THREAD

**Issue by foxale** [dbt-msft/dbt-sqlserver#296]
I think it would be super cool to see [Elementary](https://docs.elementary-data.com/introduction) together with SQL Server in action connected via [dbt-data-reliability](https://github.com/elementary-data/dbt-data-reliability) package. Any chance of it happening in the near future?

**Comment by sdebruyn** [comment]
Hi @foxale, I think this is probably an issue for the https://github.com/elementary-data/dbt-data-reliability repo
