### ISSUE TITLE
Jinja in comments are compiled

### ISSUE THREAD

**Issue by cverhoef** [dbt-msft/dbt-sqlserver#313]
When Jinja statements are put in regular SQL comments (-- or /*), the statement is still taken into account when compiling the dbt project. Potentially this results in compilation errors in commented code, which is not intuitive to debug. Especially because you may want to comment parts of the model because it results in errors.

Reproduction case (tested it only on dbt-sqlserver v1.0 and v1.1):

```
Model as (
    select
        Model_base."Field"
        -- {{ this is a jinja statement in comments }}
    from Model_base
)
```
Results in the following compilation error message:

```
15:52:52  Encountered an error:
Compilation Error in model Model (models\Model.sql)
  expected token 'end of print statement', got 'statement'
    line 12
      -- {{ this is a jinja statement in comments }}
```

**Comment by cverhoef** [comment]
Realized after creating this is also an issue in dbt-core.

**Comment by sdebruyn** [comment]
This is the intended behavior since you might want to output things from jinja to SQL comments for debugging and some comments are even interpreted by SQL Server.
