### ISSUE TITLE
Install dbt-sqlserver on MacOS Ventura 13.2 Python 3.7.16

### ISSUE THREAD

**Issue by depowell** [dbt-msft/dbt-sqlserver#335]
hey there,
i am trying to install adapter for sqlserver. however seems to be encountering issue with pyodbc package. i have tried many ways to tackle this issue, i.e. emulate rosetta terminal x86_64 architecture instead of arm64

i have tried to do following to get following erros:
 $ brew install pyenv pyenv-virutalenv

create virtual environment:
 $ pyenv virtualenv 3.7.16 dbt
 $ pyenv activate dbt
 $ pip install dbt-core
 $ pip install dbt-sqlserver

`
Building wheels for collected packages: pyodbc
  Building wheel for pyodbc (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'pyodbc' extension
      creating build
      creating build/temp.macosx-13.2-arm64-3.7
      creating build/temp.macosx-13.2-arm64-3.7/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -DPYODBC_VERSION=4.0.32 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/d.powell/.pyenv/versions/3.7.16/envs/dbt/include -I/Users/d.powell/.pyenv/versions/3.7.16/include/python3.7m -c src/buffer.cpp -o build/temp.macosx-13.2-arm64-3.7/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
      In file included from src/buffer.cpp:12:
      src/pyodbc.h:56:10: fatal error: 'sql.h' file not found
      #include <sql.h>
               ^~~~~~~
      1 error generated.
      error: command 'clang' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyodbc
  Running setup.py clean for pyodbc
Failed to build pyodbc
Installing collected packages: pyodbc, PyJWT, portalocker, cryptography, azure-core, msal, msal-extensions, azure-identity, dbt-sqlserver
  Running setup.py install for pyodbc ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyodbc did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running install
      running build
      running build_ext
      building 'pyodbc' extension
      creating build
      creating build/temp.macosx-13.2-arm64-3.7
      creating build/temp.macosx-13.2-arm64-3.7/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -DPYODBC_VERSION=4.0.32 -UMAC_OS_X_VERSION_10_7 -I/usr/local/include -I/Users/d.powell/.pyenv/versions/3.7.16/envs/dbt/include -I/Users/d.powell/.pyenv/versions/3.7.16/include/python3.7m -c src/buffer.cpp -o build/temp.macosx-13.2-arm64-3.7/src/buffer.o -Wno-write-strings -Wno-deprecated-declarations
      In file included from src/buffer.cpp:12:
      src/pyodbc.h:56:10: fatal error: 'sql.h' file not found
      #include <sql.h>
               ^~~~~~~
      1 error generated.
      error: command 'clang' failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyodbc

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
`

**Comment by depowell** [comment]
have solved by following instruction here and reinstalling pyodbc package with pip:
https://github.com/mkleehammer/pyodbc/wiki/Install

export LDFLAGS="-L/opt/homebrew/Cellar/unixodbc/[your version]/lib"
export CPPFLAGS="-I/opt/homebrew/Cellar/unixodbc/[your version]/include"
pip uninstall pyodbc
pip install pyodbc
pip install dbt-sqlserver

**Comment by sdebruyn** [comment]
seems to be a pyodbc issue, we also changed the pyodbc constraints which might help with this
