### ISSUE TITLE
setup.py includes the wrong requirement for dbt-core

### ISSUE THREAD

**Issue by RyanChapman2x** [dbt-msft/dbt-sqlserver#348]
As of `dbt-sqlserver` v1.3.1, `setup.py` includes the following lines:

> install_requires=[
>      "dbt-core>=1.3.0"
> ],

This means that when installing `dbt-sqlserver` using any package manager the wrong version of `dbt-core` will always be installed. This currently leads to incompability issues since `dbt-core` is at v1.5.0 but only v1.3.0 is supported. Users should expect to see the following errors when using `dbt debug` and `dbt run`:

> module 'dbt.exceptions' has no attribute 'DatabaseException'

To fix, `setup.py` should be changed to:

> install_requires=[
>      "dbt-core==1.3.0"
> ],

**Comment by l-j** [comment]
You are right, I have also experienced this problem. We can go even further and allow compatible versions with the `~=` operator:
```
install_requires=[
"dbt-core~=1.3.0"
],
```

**Comment by AdamG30** [comment]
This issue has rendered the adapter useless for the time being. Is there a work around way to install dbt-sqlserver?

**Comment by AdamG30** [comment]
@l-j Ok. Great. Thanks for the fast response!
