### ISSUE TITLE
Incorrect curly braces handling in `password` field in `profiles.yml`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-msft/dbt-sqlserver#433]
Could you try reproducing the following within dbt-sqlserver?

I am transferring this from https://github.com/dbt-labs/dbt-core/issues/8192 as reported by @Trymzet since I [wasn't able to reproduce](https://github.com/dbt-labs/dbt-core/issues/8192#issuecomment-1654964631) the issue using dbt-postgres.

If it turns out to be an issue in dbt-core, we can transfer it back 🙏 

### Current Behavior

`dbt debug` fails when the password contains curly braces inside, eg. `my{curly}pw123`. I validated this by running with the same password but one of the braces removed.

### Expected Behavior

I would expect special characters to be escaped within dbt so it sends the correct password to my database.

### Steps To Reproduce

Tested on `sqlserver` extension.

### Relevant log output

```shell
Database Error
  ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'my_user'. (18456) (SQLDriverConnect)")
```

### Environment

```markdown
- OS: Ubuntu 22.04
- Python: 3.10.6
- dbt:
Core:
  - installed: 1.3.2
Plugins:
  - sqlserver: 1.3.1
(1.3.2 are incompatible with each other (sic!) so I had to downgrade dbt-sqlserver)
```

### Which database adapter are you using with dbt?

other (mention it in "Additional Context")

### Additional Context

adatper used: `sqlserver`

**Comment by ryanjlind-agilitek** [comment]
did this actually get fixed in dbt-core? We are still experiencing this issue as of 1.8.9.

**Comment by ryanjlind-agilitek** [comment]
> did this actually get fixed in dbt-core? We are still experiencing this issue as of 1.8.9.

@dbeatty10 I am trying to connect to sqlserver database in dbt 1.8.9 and the password contains a curly brace (just one.) 

The login is failing and if I set the password as the username (to see what is being sent when I run dbt debug,) I can see that it is truncating the string before the brace.

For example, imagine the string is "Dr0xkw}]v/w8ds9fw7"

If I set this string as the UID, and run `dbt debug`, I get: `Login failed for user 'Dr0xkw'. (18456) (SQLDriverConnect)`

This seems to indicate to me that it is still truncating the field when it encounters a curly brace, and is why this string is not being accepted when it is the password.

**Comment by ryanjlind-agilitek** [comment]
FYI for anyone who encounters this in the future: We got around it by doubling up on the braces (replacing the `}` with `}}`) 

When reading `}}` as part of the password from `profiles.yml` it sends to the DBMS as just one `}` and the password was successfully accepted.
