### ISSUE TITLE
is this repo maintained?

### ISSUE THREAD

**Issue by sinia** [dbt-msft/dbt-sqlserver#449]
Is this repo no longer maintained? Last commit seems to be 4 months ago, also quite behind in relation to the latest dbt-core version.

Also many thanks for making this available, I found it extremely useful with dbt-core 1.4. Just want to know whether I can keep using it in the long term :)

**Comment by mhurenkamp-groveko** [comment]
You may be interested in issue #441, which explains the future support of this repo.

**Comment by cody-scott** [comment]
PR submitted for this to bring up to 1.7.2. 

related thread. 
https://github.com/dbt-msft/dbt-sqlserver/issues/441#issuecomment-1863269624
