### ISSUE TITLE
Fabric version of dbt-sqlserver

### ISSUE THREAD

**Issue by cody-scott** [dbt-msft/dbt-sqlserver#456]
First of all, sad this isn’t updated anymore, but understand it becoming a downstream version of the fabric package. 

Any word on making this in line with that version, or a discussion around if the upstream package is mature enough to start building off it?

the announcement was from the summer and nothing since then…

**Comment by namur007** [comment]
I started a discussion here:
https://github.com/microsoft/dbt-fabric/issues/86

If this adapter is stale (and not being updated), perhaps we can open a discussion around a fork of this that brings it up to the current 1.7 version (and beyond).

**Comment by unstoppable-allensun** [comment]
Looks like the Fabric adapter has been updated to support dbt 1.7 now so anyone going to start working on forking that to update this adapter?

**Comment by cody-scott** [comment]
PR has been submitted to bring up to 1.7.2 and use fabric.
https://github.com/dbt-msft/dbt-sqlserver/pull/461
