### ISSUE TITLE
Regression in 1.7.2rc2 - WITH inside custom tests

### ISSUE THREAD

**Issue by matsonj** [dbt-msft/dbt-sqlserver#470]
When invoking custom tests in the previous version, the generated SQL looks like this:

```
select
      
      count(*) as failures,
      case when count(*) != 0
        then 'true' else 'false' end as should_warn,
      case when count(*) != 0
        then 'true' else 'false' end as should_error
    from (
      
      select *
      from "db_name"."dbo_dbt_test__audit"."custom_test_name"
  
    ) dbt_internal_test
    
```
however, in 1.7.2rc2, it generates SQL like this:
    
```
select
      
      count(*) as failures,
      case when count(*) != 0
        then 'true' else 'false' end as should_warn,
      case when count(*) != 0
        then 'true' else 'false' end as should_error
    from (
      
      <test_definition.sql>
  
    ) dbt_internal_test
    
```

Since it is dropping the raw SQL query into the executed SQL query, this breaks any custom tests that use CTEs. 

Workaround: Don't use CTEs in custom tests.

**Comment by pl-pr** [comment]
@matsonj 
If you want to use CTEs in custom tests, start your code with `WITH`. Then it works correctly. Perhaps you have a comment in SQL format `/*.... */` or `--....`, then change it to the Jing format `{#.... #}`.

**Comment by matsonj** [comment]
The custom test appropriately uses as CTE. The problem is in 1.4 (previous version), the test was first added as a view and then executed. In 1.7, the test is tested directly with a subquery, which means you cannot use CTEs inside of custom tests.

**Comment by pl-pr** [comment]
When your custom test begins with the word `with` a view is also created. 
https://github.com/microsoft/dbt-fabric/blob/main/dbt/include/fabric/macros/materializations/tests/helpers.sql#L3
Are you sure ur code doesn't contain anything before the word `with`
Here is an example of a test with a CTE
![obraz](https://github.com/dbt-msft/dbt-sqlserver/assets/113114133/ca972b6e-0b6c-473e-ae83-b0e173b40af4)

**Comment by pl-pr** [comment]
When your custom test begins with the word `with` a view is also created
https://github.com/microsoft/dbt-fabric/blob/main/dbt/include/fabric/macros/materializations/tests/helpers.sql#L3
Are you sure your code doesn't contain anything before the word `with` , any comments etc.

**Comment by matsonj** [comment]
@pl-pr I will provide more notes here shortly. Thanks for the feedback

**Comment by G14rb** [comment]
@matsonj unfortunately it's because of the dependency to dbt-fabric. This, like many other errors, is fixed in the version 1.8.0
https://github.com/microsoft/dbt-fabric/commit/57f2aa60ef9f60f5bf2a065fd508c5c3335b6ea1

**Comment by cody-scott** [comment]
I've pushed a changed to swap it to using a regex search instead of the `with` statement. If you'd like to test on your models please feel free.
https://github.com/dbt-msft/dbt-sqlserver/pull/518

**Comment by cody-scott** [comment]
Should be closed by https://github.com/dbt-msft/dbt-sqlserver/pull/518
