### ISSUE TITLE
Dev container fails to start

### ISSUE THREAD

**Issue by hogank3** [dbt-msft/dbt-sqlserver#484]
Initially I was trying to clone the repository to a dev container which was failing. It is not clear from the error but it was caused by the test.env file missing in the .devcontainer directory since that is not included in the repo.

![image](https://github.com/dbt-msft/dbt-sqlserver/assets/56086965/7a9df878-0d81-40f9-ab39-2f24c43c71d8)

So instead, I cloned the repo, added a test.env file, then opened the local folder in a container. This allowed the container to build finally but then had an issue with a postStartCommand because the test.env also needed to be present in the root directory of the repo.

![image](https://github.com/dbt-msft/dbt-sqlserver/assets/56086965/60f8788b-ec07-4f9c-b302-d1eab4b83e85)

Maybe some additional detail in the Devcontainer section of [CONTRIBUTING.md](https://github.com/dbt-msft/dbt-sqlserver/blob/master/CONTRIBUTING.md#devcontainer) would help? It's not super clear what manual steps need to be done first before you can spin a up a container. Thanks again to those who jumped in on the [dbt Slack](https://getdbt.slack.com/archives/CMRMDDQ9W) to help me out!

**Comment by schlich** [comment]
closed by #489
