### ISSUE TITLE
Create table as has extra drop relation statement

### ISSUE THREAD

**Issue by cody-scott** [dbt-msft/dbt-sqlserver#488]
Removed the additional drop relation in https://github.com/dbt-msft/dbt-sqlserver/blob/master/dbt/include/sqlserver/macros/materializations/models/table/create_table_as.sql#L12

I don't believe this resolves the issue noted here, but its a good cleanup.
https://github.com/dbt-msft/dbt-sqlserver/discussions/481

When running a run with the following model it generates two drops

```sql
{{
    config(
        materialized='incremental'
    )
}}

select
    *

from dbo.tst

{% if is_incremental() %}

  -- this filter will only be applied on an incremental run
  -- (uses >= to include records whose timestamp occurred since the last run of this model)
  where DT >= (select DATEADD(MINUTE, -20, max(DT)) from {{ this }})

{% endif %}
```

DROPS

```sql
USE [TestDB];
EXEC('DROP view IF EXISTS "dbt"."incremental_mdl__dbt_tmp_temp_view";');
```

```sql
USE [TestDB];
EXEC('DROP table IF EXISTS "dbt"."incremental_mdl__dbt_tmp";');
```

**Comment by schlich** [comment]
Closed by #489

**Comment by clegendre** [comment]
Hi !
This drop was useful.
The `incremental_mdl__dbt_tmp` table stay in the database, and subsequent runs fails.

**Comment by clegendre** [comment]
Hi and sorry for the reminder, but this is still very annoying. Could you explain why you did remove this extra drop ?

**Comment by ms32035** [comment]
@cody-scott @schlich I also see an issue with this. I did an upgrade to the latest `dbt-fabric` here https://github.com/dbt-msft/dbt-sqlserver/pull/502, and because of this line removed, I have one failing test `TestIncrementalGrantsSQLServer`
