### ISSUE TITLE
is this project still activelly developed?

### ISSUE THREAD

**Issue by sinia** [dbt-msft/dbt-sqlserver#511]
It would be great to have some indication of whether this project can be relied upon in the foreseeable future, specifically whether bugs will be actively resolved and development will continue.

**Comment by nickteff** [comment]
This package is great and I too would like to know about its future.  Thanks for all of your efforts!

**Comment by nickteff** [comment]
btw, I just found [this issue](https://github.com/dbt-msft/dbt-sqlserver/issues/441) which spells out the future.

**Comment by cody-scott** [comment]
I'll comment that I did have some changes, but I've not seen anything from @schlich in awhile.

@schlich any word on the support? Sounded like you were the primary person after @sdebruyn now

**Comment by schlich** [comment]
I switched jobs to a job that does not use SQL Server not too long after taking the lead on the last major upgrade, which means I don't have the capacity/motivation to actively maintain the repo. I can tend to pull requests to the best of my ability (i'm not sure if there's any other active contributors with the ability to do so), but I have definitely not been able to organize bug fixes and new updates, etc. I believe I also don't have the ability to name admins/maintainers in the github organization, but if someone is willing to take up the torch I can try to see what we need to do to pass it on.

for now, tagging me on here is probably the best way to get my attention if active help is needed (I have a little more time for side quests now that i've settled into the new job a bit, but not too much)

but I'm not aware of any active developments or maintenance work happening, to try to answer the original question.

**Comment by cody-scott** [comment]
@schlich I'm happy to pick up the mantle of admining this if its an option. We will be using for the foreseeable future.
I've got a branch implementing all the tests for the current version and fixing a few of the regressions. It will likely conflict with the #502 merge though

**Comment by schlich** [comment]
@cody-scott congratulations, you are now an admin 🙂
