### ISSUE TITLE
Materialized Table do not Contain Columnstore Index

### ISSUE THREAD

**Issue by zcecc22** [dbt-msft/dbt-sqlserver#545]
Materialized tables created with latest stable do not get any columnstore index.

Using as_columnstore: True does not solve the issue either.

Running SQL Server 2022 Developer.

Thanks for your support,
Vincent

![image](https://github.com/user-attachments/assets/29c7010a-1319-42a2-9131-b55d798b869c)

Model:

 SELECT
  CAST(MATERIAL AS int) AS [Material],
  CAST(PLANT AS varchar(40)) AS [Plant],
  CAST(STOR_LOC AS varchar(40)) AS [Storage Location],
  CAST(DEL_FLAG AS varchar(40)) AS [Deletion Flag],
  CAST(STRGE_BIN AS varchar(40)) AS [Storage Bin],
  TRY_CAST(REPLACE([_-BIC_-ZLABST], ',', '') AS float) AS [Unrestricted Stock],
  TRY_CAST(REPLACE([_-BIC_-ZINSME], ',', '') AS float) AS [Quality Inspection Stock],
  TRY_CAST(REPLACE([_-BIC_-ZBLCKSTK], ',', '') AS float) AS [Blocked Stock],
  TRY_CAST(REPLACE([_-BIC_-ZKLABS], ',', '') AS float) AS [Consignment Unrestricted Stock],
  TRY_CAST(REPLACE([_-BIC_-ZKINSM], ',', '') AS float) AS [Consignment Quality Inspection Stock],
  TRY_CAST(REPLACE([_-BIC_-ZKSPEM], ',', '') AS float) AS [Consignment Blocked Stock]
FROM {{ source('sources', 'bw_mard') }}

dbt_project.yml:

models:
  sp_dbt_sqlserver:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: table
      +schema: staging

packages.yml:

packages:
  - package: dbt-msft/tsql_utils
    version: 1.2.0

**Comment by zcecc22** [comment]
Double checked again with a clean environment and same issue. The tables created have no columnstore.

**Comment by cody-scott** [comment]
Can you run `dbt debug` and confirm the version.

**Comment by zcecc22** [comment]
It was a package version issue. My pyproject.toml referenced dbt-sqlserver-dyvenia as dependency which pointed to version 1.7.3... Not sure if I should be concerned after using this package.

With dbt-sqlserver 1.8.0 no issue

**Comment by cody-scott** [comment]
Not sure what the `dbt-sqlserver-dyvenia` package is, but the one we publish is just `dbt-sqlserver`. 

https://docs.getdbt.com/docs/core/connect-data-platform/mssql-setup

I would _probably not trust_ the dyvenia one, if it was me.
