### ISSUE TITLE
Incorrect syntax near the keyword 'as' in creation of catalog

### ISSUE THREAD

**Issue by simonhoerdumbonde** [dbt-msft/dbt-sqlserver#556]
Hi

I'm trying out my model wity the latest release of dbt-sqlserver i.e. 1.8.2 and the model runs but I cannot create documentation.
When I run `dbt docs generate` it fails with the error `Incorrect syntax near the keyword 'as'`.

Looking at the log the issue seems to come from the macro `sqlserver__get_catalog`.
With my model the _cols_ CTE compiles to

```
cols as (
    select
        c.object_id,
        c.name as column_name,
        c.column_id as column_index,
        t.name as column_type
    from sys.columns as c with (nolock)
    left join sys.types with (nolock) as t on c.system_type_id = t.system_type_id
)
```

Moving the table aliasing `as t` to be before  `{{ information_schema_hints() }}` here `with (nolock)` resolves the issue with the query not running for me.

**Comment by cody-scott** [comment]
https://github.com/dbt-msft/dbt-sqlserver/blob/master/dbt/include/sqlserver/macros/adapter/catalog.sql#L99 This line here right?

**Comment by simonhoerdumbonde** [comment]
Yes, I just created a PR to change it. #557
