### ISSUE TITLE
ImportError: cannot import name 'get_pyodbc_attrs_before' from 'dbt.adapters.fabric.fabric_connection_manager' 

### ISSUE THREAD

**Issue by jasonwhitehouse-1** [dbt-msft/dbt-sqlserver#581]
Hi all,

I've been using Github actions to schedule my dbt run for the past few months with no issues. However, over the weekend it failed with the following error:

ImportError: cannot import name 'get_pyodbc_attrs_before' from 'dbt.adapters.fabric.fabric_connection_manager' (/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/dbt/adapters/fabric/fabric_connection_manager.py)

Any ideas what's caused this, or how best to fix it?

Thanks,
Jason

**Comment by cody-scott** [comment]
Fabric pushed an update yesterday that changed that function name. Will try to fix today, but you can pin the version <1.8.8 as a temp fix.
