### ISSUE TITLE
dbt-adapter-test test_dbt_snapshot_strategy_check_cols failing

### ISSUE THREAD

**Issue by swanderz** [dbt-msft/dbt-sqlserver#61]
This is the only test (besides `data_test_ephemeral_models`) that isn't passing CI. [relevant Circle CI run](https://app.circleci.com/pipelines/github/dbt-msft/dbt-synapse/90/workflows/be73e2d3-f70f-45ef-976d-a1be93888a8f/jobs/97/steps) for those who belong to dbt-MSFT org. Here's [the full gist](https://gist.github.com/swanderz/3dc131dbd9b28e71e345e4354231fd8f) from CircleCI that includes all the SQL executed when only this test is run and no others. Below is the pytest result summary.

Perhaps the merge functionality isn't working properly and it's only inserting or only updating?

```python
============================= test session starts ==============================
platform linux -- Python 3.7.9, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /root/project/.tox/integration-synapse/bin/python
cachedir: .pytest_cache
rootdir: /root/project
plugins: dbt-adapter-0.3.0
collecting ... collected 1 item                                                               

test/integration/sqlserver.dbtspec::test_dbt_snapshot_strategy_check_cols FAILED [100%]

=================================== FAILURES ===================================
________________ usecase: test_dbt_snapshot_strategy_check_cols ________________
Unknown error: expected cc_all_snapshot to have 30 rows, but it has 20
assert Decimal('20') == 30
  +Decimal('20')
  -30 in test index 12 (item_type=relation_rows)
```

**Comment by mikaelene** [comment]
The bug here was that we were using a dbt_scd_id of id + cast(get date() as varchar). The casting of get date removed the milliseconds. When the test runs the get date cast gets the same value as the previously inserted record so the merge that are looking for different dbt_scd_ids did not find it. The change above increases precision in the get_date cast and solvs the problem.
