### ISSUE TITLE
Add application name to ODBC string

### ISSUE THREAD

**Issue by jtcohen6** [dbt-msft/dbt-sqlserver#63]
Microsoft collects anonymous aggregate statistics about SQLServer + Synapse usage via the "Application Name" property of connections. After we spoke with a Synapse PM the other day, they're curious to know how many people are using dbt with SQLServer + Synapse.

If you're open to it, I believe we can add an `APP` parameter to the ODBC connection string. For reference:

- [SQL Server docs](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/applications/using-connection-string-keywords-with-sql-server-native-client?view=sql-server-ver15#odbc-driver-connection-string-keywords)
- Similar code in `dbt-spark`: we pass a [useragent for ODBC connections to Databricks](https://github.com/fishtown-analytics/dbt-spark/blob/cde01217aa78451fb4d7b906e1c1bec2ec6edf5a/dbt/adapters/spark/connections.py#L352)

**Comment by swanderz** [comment]
Totally doable, IMHO. this might also dovetail with https://github.com/dbt-msft/dbt-synapse/issues/18 in that the `APP` param could depend on which product is specified in the `profiles.yml`?

**Comment by mikaelene** [comment]
we could maybe send "dbt"+ `adapter name from profiles.yml`

**Comment by jtcohen6** [comment]
@mikaelene @swanderz Would you be up for getting this in before the v0.19.0 release? I think sending `'dbt'` + `credentials.type()` makes a lot of sense!

**Comment by mikaelene** [comment]
I can look into that before release

**Comment by mikaelene** [comment]
Solved with #63
