### ISSUE TITLE
fix AAD integrated authentication

### ISSUE THREAD

**Issue by swanderz** [dbt-msft/dbt-sqlserver#68]
using `authentication: ActiveDirectoryIntegrated` doesn't work. most likely due to this chunk not helping anything just causing problems. @NandanHegde15 is in the process of testing will open a PR to resolve this ASAP.
https://github.com/dbt-msft/dbt-sqlserver/blob/f98edd015b252fbd7eb5acd2bd4c28d49e746d6f/dbt/adapters/sqlserver/connections.py#L153-L155

**Comment by mikaelene** [comment]
@swanderz  Should we include this in next release?

**Comment by swanderz** [comment]
Yeah that'd be ideal! We hope to add less-technical users to our projects soon. Giving access via AAD is way more secure and simple than SQL account.

 While the fix itself is simple, @NandanHegde15 has been working on how we can test in CircleCI that `ActiveDirectoryIntegrated` is working with our test Azure tenant and an Azure VM. Though maybe if we can't get that finished in the next few days, we can merge this PR (after manually testing of course), cut a new release, and address the CI testing in a future PR and release.

**Comment by mikaelene** [comment]
@swanderz can this be closed?

**Comment by swanderz** [comment]
> @swanderz can this be closed?

I'll close it now. For posterity, here's our recommendation:
> no one should use `ActiveDirectoryIntegrated`, unless they have an:
> - on-prem Active Directory, or 
> - Azure Active Directory with Active Directory Federation Services (ADFS) enabled.
