### ISSUE TITLE
Conventions for Python code

### ISSUE THREAD

**Issue by JCZuurmond** [dbt-msft/dbt-sqlserver#72]
Let's decide on which conventions to apply for Python code.

Issue originates from discussion about python import order

I'll put them back in the same order and open a separate PR for this. I do not care too much either. The following resources are useful:

According to [PEP8](https://www.python.org/dev/peps/pep-0008/#imports), Python imports should be on separate lines (per library) and the imports are grouped in three blocks:
1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

Next to that, it is common to sort the imports within on of these three group alphabetically - to improve searchability. Finally, [some](https://stackoverflow.com/questions/20762662/whats-the-correct-way-to-sort-python-import-x-and-from-x-import-y-statement) put the `import ...` before `from ... import ...`, or vice versa or mix them.

_Originally posted by @JCZuurmond in https://github.com/dbt-msft/dbt-sqlserver/pull/71#discussion_r550109445_

**Comment by swanderz** [comment]
I know @mikaelene is partial to `black` and that the `dbt-core` team uses `flake8`. Happy to discuss any changes via a PR with incremental changes.

**Comment by sdebruyn** [comment]
Pre-commit config was added, follows style similar to dbt-core
