### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by jfallt** [dbt-msft/dbt-sqlserver#86]
I received the following error when attempting to connect to my database (localhost):

Database Error ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: No connection could be made because the target machine actively refused it.\r\n (10061) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (10061)'

I'm using dbt and dbt-sqlserver v0.18.1

**Comment by jfallt** [comment]
I resolved this by checking my TCP settings

Sql Server Configuration Manager -> Sql Server Network Configuration -> Protocols For -> TCP/IP

Make sure TCP is enabled 🥳

**Comment by swanderz** [comment]
posterity thanks you @jfallt!
