### ISSUE TITLE
Creating Indexed Views

### ISSUE THREAD

**Issue by alittlesliceoftom** [dbt-msft/dbt-sqlserver#90]
In SQL Server we can have indexed views to add speed without needing to recreate data. 

However if we try and add these with post hooks we'll get this error: 

`Cannot create index on view 'YourModel' because the view is not schema bound. (1939) (SQLExecDirectW)")`

To solve this we need to add `WITH SCHEMABINDING` to the view creation statement or alter it. The simplest way I can think to do this is to add this line to the config: 
`
with":"SCHEMABINDING",
`
Which then would also support some other with statements. 

e.g. 
https://stackoverflow.com/questions/8506487/cannot-create-index-on-view-view-table-name-because-the-view-is-not-schema-bou

Happy to implement if @mikaelene can give me a pointer on where to start?

**Comment by swanderz** [comment]
just learning about materialized views and `SCHEMABINDING`-- looks pretty cool and valuable. Is my interpretation of the snippet below correct in that if you make a materialized view, then the upstream table cannot be changed unless you first change the downstream view? That raises alarm bells for me, but not sure if it's really a problem

### [docs snippet](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-view-transact-sql?view=sql-server-ver15&WT.mc_id=DP-MVP-5003930)

> `SCHEMABINDING`
> Binds the view to the schema of the underlying table or tables. When `SCHEMABINDING` is specified, the base table or tables cannot be modified in a way that would affect the view definition. The view definition itself must first be modified or dropped to remove dependencies on the table that is to be modified. When you use `SCHEMABINDING`, the `select_statement` must include the two-part names (`schema.object`) of tables, views, or user-defined functions that are referenced. All referenced objects must be in the same database.
> 
> Views or tables that participate in a view created with the `SCHEMABINDING` clause cannot be dropped unless that view is dropped or changed so that it no longer has schema binding. Otherwise, the Database Engine raises an error. Also, executing `ALTER TABLE` statements on tables that participate in views that have schema binding fail when these statements affect the view definition.


### implementation

If a user wants to make a materialized view to the `revenue.sql` model,  they would add the following to their `dbt_project.yml` (or as a config block at the top of the model file). If we're playing by the books, we should also implement something that tells a user when they're trying to make a table but also have `schemabinding` specified.

```yaml
models:
  example_project:
    revenue:
      +materialized: view
      +schemabinding: true
```

the logic change would be to modify `sqlserver__create_view_as` to look something like the below. @alittlesliceoftom want to try this out and see if it works?

```sql
{% macro sqlserver__create_view_as(relation, sql) -%}
  {% set sb_bool = config.get('schemabinding', default=false) %}
  create view {{ relation.schema }}.{{ relation.identifier }}
  {%- if sb_bool %}
  WITH SCHEMABINDING
  {%- endif %}
   as
  {{ sql }}
{% endmacro %}
```

**Comment by mikaelene** [comment]
This part doesn't feels good 

> The view definition itself must first be modified or dropped to remove dependencies on the table that is to be modified

This means that when we drop and create the table the view is based on (since it's first in the DAG), will will get an error?!

**Comment by alittlesliceoftom** [comment]
Yeh, that will break the order of ops on a change, that would be confusing
for user.

I think you're unlikely to use the feature on a quickly changing base table
though

**Comment by mikaelene** [comment]
You mean that it would only be based on sources, snapshots or incremental models? All other dbt models are dropped and created each time.

**Comment by alittlesliceoftom** [comment]
> You mean that it would only be based on sources, snapshots or incremental models? All other dbt models are dropped and created each time.

Hmmm, that's a very good point, you'd probably end up having to shuffle things around, like re-pointing at different sources. 

The idea here is to be able to do things like apply an index to a view (perhaps representing a subset of data) and for that you need schemabinding, but I think in a scenario with a dbt model it wouldn't work. 

In my case I want to point at a source, but that's quite a limiting subset.

I'd be happy for this to close based on that feedback... :/

**Comment by mikaelene** [comment]
Yes it might be a little confusing for the users. But if you "hard-code" the index script in a post-hook adding the schema-binding etc, maybe is works as a workaround? Or just create the view as a macro executed as a dbt-runoperation. I have stuff like that when working with snowflake. I.e. setting upp file_formats for external tables.

**Comment by swanderz** [comment]
closing for now. @alittlesliceoftom feel free to re-open if you ever would like to revisit!

**Comment by alkio-netlight** [comment]
So what is the current recommendation for creating indexed views?
