### ISSUE TITLE
purpose of relation.incorporate in sqlserver__create_table_as

### ISSUE THREAD

**Issue by swanderz** [dbt-msft/dbt-sqlserver#94]
@mikaelene can you help me understand what this does? Is the idea that all temp relations are made as views instead when creating tables, by removing the `#` from the temp relation identifier?

https://github.com/dbt-msft/dbt-sqlserver/blob/7e74e971762fdbd652f2e75973a012190147120e/dbt/include/sqlserver/macros/adapters.sql#L143-L145

**Comment by mikaelene** [comment]
It looks like that :-). I think there was a problem using temptable in this materialisation. I didn't want to remove the possibility of using temptable in the adapter but could not use it here.

But I am not 100% sure why
